name: apps-postgresql-production

instance_groups:
- name: postgresql
  azs:
  - z1
  - z2
  instances: 2
  vm_type: medium
  stemcell: default
  persistent_disk_type: 128GB
  networks:
  - name: &network_name db-service
    static_ips:
    - 10.100.16.130
    - 10.100.32.130
  jobs:
  - name: postgres
    release: postgres-replica-release
    properties:
      password: ((apps_postgresql_production_root_password))
      database2: ((apps_postgresql_production_metering))
  - name: sysctl
    release: sysctl
    properties:
      sysctl_conf:
        net.ipv4.tcp_keepalive_time = 120
        net.ipv4.tcp_keepalive_intvl = 30
        net.ipv4.tcp_keepalive_probes = 8
  - name: postgres_exporter
    release: prometheus
    properties:
      postgres_exporter:
        datasource_name: postgresql://postgres:((apps_postgresql_production_root_password))@127.0.0.1:5432/postgres

variables:
- name: apps_postgresql_production_root_password
  type: password
- name: apps_postgresql_production_metering
  type: password
        
update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-20000
  update_watch_time: 1000-20000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 'latest'

releases:
- name: postgres-replica-release
  version: '1.0.12'
  url: http://wise-paas.oss-cn-beijing.aliyuncs.com/bosh-release/postgres-replica-release-1.0.12.tgz
  sha1: 8ecd8e3bd7d0b7ad34c4cfa3339f9e681155013a
- name: prometheus
  version: '22.0.0'
  url: http://wise-paas.oss-cn-beijing.aliyuncs.com/bosh-release/prometheus-boshrelease-22.0.0.tgz
  sha1: c6c9dd3530ccf94eefc70b11482e77eafc20a0ef
- name: sysctl
  version: '2'
  url: http://wise-paas.oss-cn-beijing.aliyuncs.com/bosh-release/sysctl-release-2.tgz
  sha1: 09ae3d2271630653cceec115282004bfef1c694b
  
