name: apps-postgresql-production

instance_groups:
- name: postgresql
  azs:
  - z1
  - z2
  instances: 2
  vm_type: Standard_DS2_v2
  stemcell: default
  persistent_disk_type: 128GB
  networks:
  - default:
    - dns
    - gateway
    name: &network_name db-service
    static_ips:
    - 172.22.16.30
    - 172.22.32.30
  - name: vip
    static_ips:
    - 40.83.96.85
    - 40.83.79.84
  jobs:
  - name: postgres
    release: postgres-replica-release
    properties:
      connection: 2000
      password: ((apps_postgresql_production_root_password))
      database2: ((apps_postgresql_production_metering))
  - name: sysctl
    release: sysctl
    properties:
      sysctl_conf:
        net.ipv4.tcp_keepalive_time = 120
        net.ipv4.tcp_keepalive_intvl = 30
        net.ipv4.tcp_keepalive_probes = 8
  - name: postgres_exporter
    release: prometheus
    properties:
      postgres_exporter:
        datasource_name: postgresql://postgres:((apps_postgresql_production_root_password))@127.0.0.1:5432/postgres

variables:
- name: apps_postgresql_production_root_password
  type: password
- name: apps_postgresql_production_metering
  type: password
        
update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-20000
  update_watch_time: 1000-20000

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 'latest'

releases:
- name: postgres-replica-release
  version: '1.0.12'
- name: prometheus
  version: '22.0.0'
- name: sysctl
  version: '2'
  
