name: apps-mongodb-production
releases:
  - name: &release_name mongo-shard-release
    version: '1.0.14'
    url: http://wise-paas.oss-cn-beijing.aliyuncs.com/bosh-release/mongo-shard-release-1.0.14.tgz
    sha1: 846bc9599691340bcfd131e50a47c7d85891980e
  - name: &prometheus prometheus
    version: '22.0.0'
    url: http://wise-paas.oss-cn-beijing.aliyuncs.com/bosh-release/prometheus-boshrelease-22.0.0.tgz
    sha1: c6c9dd3530ccf94eefc70b11482e77eafc20a0ef

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 'latest'

instance_groups:
- name: mongodb
  env:
    persistent_disk_fs: xfs
  instances: 3
  jobs:
  - name: mongodb
    release: *release_name
    properties:
      mongodb:
        connection: 3000
        admin:
          user: ((apps_mongodb_production_admin))
          password: ((apps_mongodb_production_admin_password))
        root:
          user: ((apps_mongodb_production_root))
          password: ((apps_mongodb_production_root_password))
        keyfile: |
          Si3ro+EPlvm+Mh51yRPW/y8Uwb+CYtRpAraffnkghK3vHbSl3D6GyZaLSrrqJf3U
          no9XyH0afUAgsUpx5nztOj+Xb3HPxvbzDkbwxCYI69NL/ckyH9J4raSEriTaxJ0B
          mA7LJicQdOXOMYGk29QsEZxfFLtWw43gVidp0FfFm8AC0LjZPvVEUHq0o4oFR+v8
          HM/tFwrfM7doCk3J8+XWVVzJ0ZIiMd+q7Ldpqr6SwIiuO0kXqbvBG3gqVjZUVc7l
          kPIxVqKdH2BcbFzdQU1P9wuQRk1gw576tx+OnS6Sbd1KcNrjN06N5zRns+7xfckT
          pIgehSkjh2N4uHF9KGn/7V953Ttn//UNPpWTvXbfn3r6Hu4AnYE+m5T+b9krIbIb
          pGP60hUXhSXkYVdMHR6AM/9HBIYxAcDBLGvOB74oNl+FH485Yk8Xja8SA8JB8iiS
          l3KYtmiOtY21JH0Ri0Tlf7TMxqoNCcpyZpPA8/ZsofBdZHrLfCpvREX6x3jKzxcF
          OLaGSncJYT024V5hEGFv6zGzehWvKi2CGn1DjFpmtRQS7G+nfoGEe1bpzyxqZmrn
          oBbBLZCEevkRC2m5XvdUcb5BkNyJhWAHVNtrXtDgdy0bYhGOBnaf3MVCjvAh1ybH
          MucmQF5JaoSd3eMaOJFueZw9M1bIqtvq6xxCN2Rw9jyPYwueg5gvMY7AU/QmbPlZ
          gc2vXZ60Xb42AZJ84JeptTp+OchW99ONAmsaZPMh7xX7WbyMdr/Nn6Ts9AiloPib
          FhmWpqjLagztuYKUrRy7t3hc06K6jxcidMJ2kj1mC7cCun5wxEK1/kKGtD1xr1/B
          7ZcAiHMa9NjBjz/0DXX0tCWOxj3A/IULIBTbu3SXdbeL7u9YlKHCC16d8i1udWbz
          lcTXL7ADYw/xYiCuyElARxMdB1htiiofYhzkxRMsW0ri1u1WwTwGFrSCeo70Cops
          5oqcP9b4yujo/3eMKZ64E4kFTXL3jSxCkRW8BgsRq7zReazk
  - name: mongodb_exporter
    release: prometheus
    properties:
      mongodb_exporter:
        mongodb:
          uri: mongodb://((apps_mongodb_production_root)):((apps_mongodb_production_root_password))@127.0.0.1:27017
          
  vm_type: medium
  persistent_disk_type: 512GB
  stemcell: trusty
  networks:
  - default:
    - dns
    - gateway
    name: &network_name db-service
    static_ips:
    - 10.100.16.110
    - 10.100.32.110
    - 10.100.48.110
  azs:
   - z1
   - z2
   - z3

variables:
- name: apps_mongodb_production_root
  type: password
- name: apps_mongodb_production_root_password
  type: password
- name: apps_mongodb_production_admin
  type: password
- name: apps_mongodb_production_admin_password
  type: password


update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
