name: ops-influxdb-production
releases:
  - name: &release_name influxdb
    version: '1.7.10'

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 'latest'

instance_groups:
- name: influxdb
  env:
    persistent_disk_fs: xfs
  instances: 1
  jobs:
  - name: influxdb
    release: *release_name
  - name: chronograf
    release: *release_name
  - name: telegraf
    release: *release_name
  - name: kapacitor
    release: *release_name
  vm_type: medium
  persistent_disk_type: 100GB
  stemcell: default
  networks:
  - default:
    - dns
    - gateway
    name: &network_name db-service
    static_ips:
    - 172.22.16.21
  - name: vip
    static_ips:
    - 13.75.69.156
  azs:
  - z1

properties:
  influxdb:
    admin:
      user: ((ops_influxdb_production_root))
      password: ((ops_influxdb_production_root_password))
    database: test

variables:
- name: ops_influxdb_production_root
  type: password
- name: ops_influxdb_production_root_password
  type: password
    
update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
