name: ops-influxdb-healthcheck
releases:
  - name: &release_name influxdb
    version: '1.0.14'
    url: http://wise-paas.oss-cn-beijing.aliyuncs.com/bosh-release/influxdb-release-1.0.14.tgz
    sha1: b8c4091ef0631f59c841cb88332c2adaba84a9c8
    
stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 'latest'

instance_groups:
- name: influxdb
  instances: 1
  jobs:
  - name: influxdb
    release: *release_name
    properties:
      influxdb:
        admin:
          user: ((apps_influxdb_production_root))
          password: ((apps_influxdb_production_root_password))    
  - name: chronograf
    release: *release_name
  - name: telegraf
    release: *release_name
    properties:
      influxdb:
        admin:
          user: ((apps_influxdb_production_root))
          password: ((apps_influxdb_production_root_password))    
  - name: kapacitor
    release: *release_name
    properties:
      influxdb:
        admin:
          user: ((apps_influxdb_production_root))
          password: ((apps_influxdb_production_root_password))    
  vm_type: small-lowmem
  persistent_disk_type: 512GB
  stemcell: trusty
  networks:
  - default:
    - dns
    - gateway
    name: &network_name db-service
    static_ips:
    - 10.100.48.122
  azs:
  - z3

properties:
  influxdb:
    admin:
      user: ((ops_influxdb_production_root))
      password: ((ops_influxdb_production_root_password))
    database: test

variables:
- name: ops_influxdb_production_root
  type: password
- name: ops_influxdb_production_root_password
  type: password
    
update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
