name: ops-postgresql-production

instance_groups:
- name: redis_psql
  azs:
  - z1
  - z2
  env:
    persistent_disk_fs: xfs
  instances: 2
  vm_type: Standard_DS2_v2
  stemcell: default
  persistent_disk_type: 128GB
  networks:
  - default:
    - dns
    - gateway
    name: &network_name db-service
    static_ips:
    - 172.22.16.40
    - 172.22.32.40
  - name: vip
    static_ips:
    - 40.83.76.167
    - 40.83.77.133
  jobs:
  - name: redis
    release: postgres-replica-release
    properties:
      password: ((ops_postgresql_production_redis_6379))
  - name: redis2
    release: postgres-replica-release
    properties:
      password: ((ops_postgresql_production_redis_6380))
  - name: redis3
    release: postgres-replica-release
    properties:
      password: ((ops_postgresql_production_redis_6381))
#  - name: redis-sentinel
#    release: postgres-replica-release
#    properties:
#      redis:
#        port: 6379
#        password: ((ops_postgresql_production_redis_6379))
#      redis2:
#        port: 6380
#        password: ((ops_postgresql_production_redis_6380))
#      redis3:
#        port: 6381
#        password: ((ops_postgresql_production_redis_6381))
  - name: postgres
    release: postgres-replica-release
    properties:
      password: ((ops_postgresql_production_root_password))
      connection: 2000
      metering:
        database: ((ops_postgresql_production_billing))
        username: ((ops_postgresql_production_billing_root))
        password: ((ops_postgresql_production_billing_root_password))
      sso:
        database: ((ops_postgresql_production_sso))
        username: ((ops_postgresql_production_sso_root))
        password: ((ops_postgresql_production_sso_root_password))
  - name: postgres_exporter
    release: prometheus
    properties:
      postgres_exporter:
        datasource_name: postgresql://postgres:((ops_postgresql_production_root_password))@127.0.0.1:5432/postgres
  - name: sysctl
    release: sysctl
    properties:
      sysctl_conf:
        net.ipv4.tcp_keepalive_time = 120
        net.ipv4.tcp_keepalive_intvl = 30
        net.ipv4.tcp_keepalive_probes = 8        

variables:
- name: ops_postgresql_production_root_password
  type: password
- name: ops_postgresql_production_billing
  type: password
- name: ops_postgresql_production_billing_root
  type: password
- name: ops_postgresql_production_billing_root_password
  type: password
- name: ops_postgresql_production_sso
  type: password
- name: ops_postgresql_production_sso_root
  type: password
- name: ops_postgresql_production_sso_root_password
  type: password
- name: ops_postgresql_production_redis_6379
  type: password
- name: ops_postgresql_production_redis_6380
  type: password
- name: ops_postgresql_production_redis_6381
  type: password

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-20000
  update_watch_time: 1000-20000

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 'latest'

releases:
- name: postgres-replica-release
  version: '1.0.12'
- name: prometheus
  version: '22.0.0'
- name: sysctl
  version: '2'
