name: apps-postgresql-stage

instance_groups:
- name: postgresql
  env:
    persistent_disk_fs: xfs
  azs:
  - z1
  - z2
  instances: 2
  vm_type: medium
  stemcell: default
  persistent_disk_type: 128GB
  networks:
  - name: &network_name db-service
    static_ips:
    - 10.100.31.1
    - 10.100.31.2
  jobs:
  - name: postgres
    release: postgres-replica-release
    properties:
      password: ((apps_postgresql_production_rootpassword))
      database2: ((apps_postgresql_production_metering))
#  - name: sysctl
#    release: sysctl
#    properties:
#      sysctl_conf:
#        net.ipv4.tcp_keepalive_time = 120
#        net.ipv4.tcp_keepalive_intvl = 30
#        net.ipv4.tcp_keepalive_probes = 8
  - name: postgres_exporter
    release: prometheus
    properties:
      postgres_exporter:
        datasource_name: postgresql://postgres:((apps_postgresql_production_rootpassword))@127.0.0.1:5432/postgres

variables:
- name: apps_postgresql_production_rootpassword
  type: password
- name: apps_postgresql_production_metering
  type: password
        
        
update:
  canaries: 1
  max_in_flight: 10
  serial: true
  canary_watch_time: 1000-20000
  update_watch_time: 1000-20000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 'latest'

releases:
- name: postgres-replica-release
  version: '1.0.12'
- name: prometheus
  version: '19.0.0'
#- name: sysctl
#  version: '2'
  
