name: ops-influxdb-stage
releases:
  - name: &release_name influxdb
    version: '1.7.10'
  - name: prometheus
    version: '19.0.0'

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 'latest'

instance_groups:
- name: influxdb
  instances: 1
  jobs:
  - name: influxdb
    release: *release_name
  - name: chronograf
    release: *release_name
  - name: telegraf
    release: *release_name
  - name: kapacitor
    release: *release_name
  - name: prometheus
    release: prometheus
  vm_type: medium
  persistent_disk_type: 512GB
  stemcell: trusty
  networks:
  - default:
    - dns
    - gateway
    name: &network_name db-service
    static_ips:
    - 10.100.23.1
  azs:
  - z1

properties:
  influxdb:
    admin:
      user: ((ops_influxdb_stage_root))
      password: ((ops_influxdb_stage_rootpassword))
    database: test

variables:
- name: ops_influxdb_stage_root
  type: password
- name: ops_influxdb_stage_rootpassword
  type: password
    
update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
